name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: false
          role-skip-session-tagging: true

      - name: Verify AWS Credentials
        run: |
          aws sts get-caller-identity || echo "❌ AWS credentials not found!"
          aws configure list
          cat ~/.aws/credentials || echo "❌ ~/.aws/credentials file missing!"

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        env:
          REACT_APP_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          REACT_APP_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REACT_APP_AWS_REGION: ${{ secrets.AWS_REGION }}
          REACT_APP_AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        run: |
          CI=false npm run build

      - name: Deploy to AWS S3
        env:
          AWS_SDK_LOAD_CONFIG: 1
        run: aws s3 sync build/ s3://${{ secrets.AWS_BUCKET_NAME }} --delete
