name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # ✅ Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # ✅ Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # ✅ Step 4: Inject AWS Secrets into `.env` File
      - name: Inject AWS Secrets into .env File
        run: |
          echo "REACT_APP_AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "REACT_APP_AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "REACT_APP_AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
          echo "REACT_APP_AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}" >> .env
          cat .env  # Debugging: Print the .env file

      # ✅ Step 5: Build Project (Ensuring .env Variables Are Available)
      - name: Build Project
        env:
          REACT_APP_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          REACT_APP_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REACT_APP_AWS_REGION: ${{ secrets.AWS_REGION }}
          REACT_APP_AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        run: |
          CI=false npm run build

      # ✅ Step 6: Configure AWS Credentials (Ensure AWS_SDK_LOAD_CONFIG=1)
      - name: Configure AWS Credentials
        run: |
          mkdir -p ~/.aws
          
          # Manually set credentials
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

          # Manually set config
          echo "[default]" > ~/.aws/config
          echo "region=${{ secrets.AWS_REGION }}" >> ~/.aws/config
          echo "output=json" >> ~/.aws/config

          # Ensure AWS CLI uses these credentials
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile default
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile default
          aws configure set region ${{ secrets.AWS_REGION }} --profile default
        env:
          AWS_SDK_LOAD_CONFIG: 1  # Ensures SDK loads credentials

      # ✅ Step 7: Test AWS Credentials
      - name: Debug AWS Credentials
        run: |
          echo "Testing AWS credentials..."
          aws sts get-caller-identity
        env:
          AWS_SDK_LOAD_CONFIG: 1  # Ensures SDK loads credentials

      # ✅ Step 8: Deploy Build to AWS S3
      - name: Deploy to AWS S3
        env:
          AWS_SDK_LOAD_CONFIG: 1  # Ensures SDK loads credentials
        run: |
          echo "Uploading build to S3..."
          aws s3 sync build/ s3://${{ secrets.AWS_BUCKET_NAME }} --delete
