name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  

      - name: Install Dependencies
        run: npm install

      - name: Manually Install AWS SDK
        run: npm install @aws-sdk/client-s3

      - name: Build Project
        run: CI=false npm run build  # Disables CI warnings during build

      - name: Check AWS CLI Version
        run: aws --version || echo "AWS CLI not found"

      - name: Update AWS CLI (if needed)
        run: |
          if ! aws --version | grep -q "aws-cli/2"; then
            echo "Updating AWS CLI..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install --update
          else
            echo "AWS CLI is already installed"
          fi

      - name: Deploy to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        run: |
          aws s3 sync ./build s3://$AWS_BUCKET_NAME --region $AWS_REGION --delete
